import { THEMES_COUNT } from '@utils/data';

export const ANIMATION_CONFIG = {
  DOT_DURATION: 0.2,
  ROTATION_DURATION: 1,
  LABEL_DURATION: 0.3,
  ROTATION_ANGLE: 360 / THEMES_COUNT,
} as const;

export const COLORS = {
  DOT_DEFAULT: '#42567A',
  DOT_ACTIVE: '#F4F5F9',
  DOT_STROKE: 'rgba(48, 62, 88, 0.5)',
  GRADIENT_START: '#3877EE',
  GRADIENT_END: '#EF5DA8',
} as const;

export const SIZING = {
  GRADIENT_LINE_Y_RATIO: 0.1,
  GRADIENT_LINE_HEIGHT_RATIO: 0.1,
  GRADIENT_LINE_MAX_HEIGHT: 200,
  LINE_STROKE_MIN_RATIO: 0.001,
  LINE_STROKE_MIN: 0.5,
  LINE_STROKE_MAX: 1.5,
  GRADIENT_LINE_MIN_RATIO: 0.003,
  GRADIENT_LINE_MIN: 3,
  GRADIENT_LINE_MAX: 5,
  DOT_RADIUS_MIN_RATIO: 0.004,
  DOT_RADIUS_MIN: 3,
  DOT_RADIUS_MAX: 6,
  SELECTED_DOT_RADIUS_MIN_RATIO: 0.015,
  SELECTED_DOT_RADIUS_MIN: 22,
  SELECTED_DOT_RADIUS_MAX: 36,
  HOVERED_DOT_SCALE: 0.9,
} as const;

export const LABEL_CONFIG = {
  OFFSET_MULTIPLIER: 2,
  VERTICAL_OFFSET_MULTIPLIER: 1.5,
  POSITION_ADJUSTMENT: 10,
  WIDTH: 200,
  HEIGHT: 60,
  PERIOD_OFFSET_X: 150,
  PERIOD_OFFSET_Y: 40,
} as const;

export const ANIMATION_EASING = {
  DOT: 'power2.out',
  ROTATION: 'power2.inOut',
} as const;
